version: '3.5'

services:
  magicmirror:
    image: bastilimbach/docker-magicmirror
    container_name: magicmirror
    network_mode: "bridge"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/opt/magic_mirror/config
      - modules:/opt/magic_mirror/modules
      - /var/log:/var/log
    ports:
        - 8888:8080
volumes:
  modules:
    driver: local
    driver_opts:
      type: none
      device: $HOME/contents/magicmirror/modules
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: $HOME/config/magicmirror
      o: bind
